### ISSUE TITLE
GlobalConfigs' "log_format" should be of type String instead of Bool.

### ISSUE THREAD

**Issue by MohammedSiddiqui** [PrefectHQ/prefect-dbt#113]
Running `dbt debug` from the CLI task with GlobalConfigs generated throws an error that log_format should be of type String and not bool.
On the other hand, setting a string value via GlobalConfigs throws an error that it should be of type bool.

https://github.com/PrefectHQ/prefect-dbt/blob/dc5f504e0ced080ddf8ceab1cc1e502c5256d9f6/prefect_dbt/cli/configs/base.py#L154

**Comment by ahuang11** [comment]
Thanks for the report; I've verified that it should be a string: https://docs.getdbt.com/reference/global-configs#log-formatting

Would you be interested in contributing a PR that changes this into:
`log_format: Optional[str] = None` and adding a simple test to test instantiating GlobalConfigs with log format set?

**Comment by MohammedSiddiqui** [comment]
Absolutely, let me look into this and I'll ping back if I face any issues setting up the development env

**Comment by ahuang11** [comment]
Thanks!
