### ISSUE TITLE
Credentials missing when using SnowflakeTargetConfigs in CLIProfile

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect-dbt#125]
# Expectation / Proposal
I define four block entities (Snowflake credentials, Snowflake connector, Snowflake target config and dbt CLI profile) and link them together. In this case credentials can be changed via block configuration.

I expect that the CLI profile holds the credential/connection information as well but it didn't. This is maybe related to the TargetConfigs which can't be linked to another block entity.

# Traceback / Example

```python
from prefect_snowflake.credentials import SnowflakeCredentials
from prefect_snowflake.database import SnowflakeConnector

from prefect_dbt.cli.credentials import DbtCliProfile
from prefect_dbt.cli.configs import SnowflakeTargetConfigs


if __name__ == "__main__":
    credentials = SnowflakeCredentials(
        user="user",
        password="password",
        account="account.region.aws",
        role="role",
    )
    credentials.save("sf-cred", overwrite=True)

    connector = SnowflakeConnector(
        schema="public",
        database="database",
        warehouse="warehouse",
        credentials=SnowflakeCredentials.load("sf-cred"),
    )
    connector.save("sf-conn", overwrite=True)

    target_configs = SnowflakeTargetConfigs(
        connector=SnowflakeConnector.load("sf-conn"), schema="TEST"
    )
    target_configs.save("dbt-targetconf", overwrite=True)

    dbt_cli_profile = DbtCliProfile(
        name="jaffle_shop",
        target="dev",
        target_configs=SnowflakeTargetConfigs.load("dbt-targetconf"),
    )
    dbt_cli_profile.save("example", overwrite=True)

    dbt_cli_profile = DbtCliProfile.load("example").get_profile()

    print(dbt_cli_profile)
```

Output:
`{'config': {}, 'jaffle_shop': {'target': 'dev', 'outputs': {'dev': {'type': 'snowflake', 'schema': 'TEST', 'threads': 4}}}}`

![image](https://user-images.githubusercontent.com/18382402/217775246-83b85a25-f11f-4277-a342-c895253f3016.png)

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-dbt/#contributing) a pull request to resolve this!

**Comment by ahuang11** [comment]
Thanks for the details! I believe this has been fixed in https://github.com/PrefectHQ/prefect-dbt/pull/115.

![image](https://user-images.githubusercontent.com/15331990/217884216-8f9e8c19-641a-4543-b5da-f8757fab0d4e.png)

**Comment by sti0** [comment]
So we need to wait for a new release then.

**Comment by sti0** [comment]
Hi @ahuang11 ,
I've tested the behavior with the latest main branch and this doesn't work for me when we specifiy a `schema` in the SnowflakeConnector (which is required) and in the Snowflake Target Config (which is optional).
This ends up in a `ValueError: The keyword, schema, has already been provided in TargetConfigs; remove duplicated keywords to continue` error.

As a workaround we could only specify it in Snowflake Connector but if we use the same Connector for different dbt Configs (or may for other things) it would be a better solution to overwrite the schema from Snowflake Connector with the schema from the target config.

**Comment by ahuang11** [comment]
Thank you for reporting this. I'll try to get this fixed soon.
