### ISSUE TITLE
Include a user agent to track prefect usage of the dbt Cloud API

### ISSUE THREAD

**Issue by sungchun12** [PrefectHQ/prefect-dbt#13]
I recommend looking at the work done in airflow's dbt Cloud integration: https://github.com/apache/airflow/pull/20998/commits/2677bac12f217804781377aba9ea225b1256512a

Look at the airflow code overall for a reference implementation: https://github.com/apache/airflow/pull/20998

**Comment by desertaxle** [comment]
Closed by #16
