### ISSUE TITLE
Add highlighting to logged dbt Cloud URIs

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-dbt#21]
Add color to dbt Cloud URIs that are logged in any of the tasks or flows in `prefect-dbt`. Prefect 2.0 doesn't currently have the ability to add color to terminal logs or the logs displayed in the UI. Additional core development is needed before this item can be implemented.

**Comment by ahuang11** [comment]
Related to https://github.com/PrefectHQ/prefect/pull/6101, but haven't had the time to write tests.
