### ISSUE TITLE
Add smart retry flow

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-dbt#24]
Create a flow that is capable of performing smart retries with dbt. @sungchun12 has an example of how to achieve this functionality here: https://github.com/sungchun12/prefect-dbt-cloud/blob/main/dbt_cloud_smart_rerun.py

**Comment by sungchun12** [comment]
Related: https://github.com/PrefectHQ/prefect-recipes/tree/main/prefect/flows/dbt/rerun-models-from-failure#handle-dbt-model-failures

**Comment by desertaxle** [comment]
Closed by #81
