### ISSUE TITLE
Create a loom demo video AFTER the integration is complete

### ISSUE THREAD

**Issue by sungchun12** [PrefectHQ/prefect-dbt#3]
Example: [here](https://www.loom.com/share/6faf5cc803bc41229d7b0b96d0026531)

**Comment by sungchun12** [comment]
To be assigned to Bela

**Comment by sungchun12** [comment]
@belasobral93

**Comment by mickaelandrieu** [comment]
Hi @sungchun12,

Do you know when a first release will be done ? AFAIK there is no tag nor release of this package and I'd like to use it in production

Regards

**Comment by sungchun12** [comment]
@mickaelandrieu We are actively working on testing to ensure the UX is solid in addition to the mechanics. 

I'm 80% confident a first release will happen in 2 weeks. 

@desertaxle what do you think?

**Comment by belasobral93** [comment]
completing by eow

**Comment by belasobral93** [comment]
@sungchun12 The loom video is [complete](https://loom.com/share/9bb1523792524b73926c2c83b3533e0f)but I'm experiencing a bug where my video isn't showing, despite having configured it in the settings. Going to give it another try this afternoon

**Comment by desertaxle** [comment]
I'm closing this since it looks like it's been completed. Feel free to reopen if that is not the case!
