### ISSUE TITLE
Edit official prefect collection docs

### ISSUE THREAD

**Issue by sungchun12** [PrefectHQ/prefect-dbt#4]
[DBT Tasks | Prefect Docs](https://docs.prefect.io/api/latest/tasks/dbt.html#dbtcloudrunjob)

current docs

[Collections Docs](https://orion-docs.prefect.io/collections/overview/#listing-in-the-collections-catalog)

**Comment by sungchun12** [comment]
Have a nice verified badge similar to tasks

**Comment by desertaxle** [comment]
`prefect-dbt` was added to the [Prefect Collections Catalog](https://docs.prefect.io/collections/catalog/) in https://github.com/PrefectHQ/prefect/pull/6186. It will be displayed on the next `prefect` release this week.

**Comment by sungchun12** [comment]
It's up and live!


![Image](https://user-images.githubusercontent.com/19176976/183981873-a32653b5-eb1e-4cf4-b8ad-47f397c332fb.png)
