### ISSUE TITLE
BigQueryTargetConfigs - invalid adapter type gcp

### ISSUE THREAD

**Issue by ross-kortx** [PrefectHQ/prefect-dbt#48]
BigQueryTargetConfigs provides an invalid dbt target type 'gcp' when writing a profiles.yml.
Using this profile target type results in an error running any dbt commands.

The valid dbt type should be bigquery.
https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile

```python
    type: Literal["gcp"] = "gcp"
    project: Optional[str] = None
    credentials: GcpCredentials
```

**Comment by ahuang11** [comment]
Thanks for reporting this! #49 should fix this.
