### ISSUE TITLE
Schema was not saved when creating TargetConfig block

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect-dbt#54]
The schema was not saved after I created a TargetConfig with Python code.

```
from prefect_dbt.cli.configs.base import TargetConfigs

myconfig = TargetConfigs(schema="abc", type="snowflake")
myconfig.save("testconf", True)
```
UI:
![image](https://user-images.githubusercontent.com/18382402/187887973-0792f802-2ed5-4e0f-b4d5-b79113d89402.png)

Version:
`prefect` v2.3.0 with `prefect-dbt` v0.2.0

**Comment by ahuang11** [comment]
Thanks for reporting this! Can you try:
```
from prefect_dbt.cli.configs.base import TargetConfigs

myconfig = TargetConfigs(schema_="abc", type="snowflake")
myconfig.save("testconf", True)
```
