### ISSUE TITLE
How to declare a DbtCliProfile Block 

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [PrefectHQ/prefect-dbt#55]
Hi 👋 
 
 I'm trying to use a DbtCliProfile block instead of defining everything in the code.
 The thing is I don't know how to register it in prefect block library.
 
 I tried to use the JSON block but got an error when loading the block.
 
```
dbt_cli_profile = DbtCliProfile.load("BLOCK_NAME").get_profile()
```

Do you have any inputs/docs on that specific point ?

Thanks

**Comment by ahuang11** [comment]
Run In the terminal:
`prefect block register -m prefect_dbt.cli.credentials`

This should make it show up on the UI. From https://orion-docs.prefect.io/concepts/blocks/#registering-blocks-for-use-in-prefect-cloud

**Comment by lucienfregosibodyguard** [comment]
It seems specific to prefect Cloud and I'm using the open source version, helm deployed version.

I did manage to register the block through a bit of python code
