### ISSUE TITLE
Add the capability to use the Pod service account instead of using .gcp credential file

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [PrefectHQ/prefect-dbt#56]
Hi again,

It would be awesome if instead of reading the .gcp json file with the credentials it would be possible to use the service account associated with the kubernetes pod.

Like we do for the GCP python client we don't need to write/specify any json file.

Can help on this point if you need it.

Thanks

**Comment by ahuang11** [comment]
Thanks for the suggestion! We would appreciate any help implementing, or simply pointers on how to do so!

**Comment by ahuang11** [comment]
Thanks for the suggestion. Do you have code snippets by any chance?

**Comment by lucienfregosibodyguard** [comment]
```
client = bigquery.Client()

query = """
    SELECT name, SUM(number) as total_people
    FROM `bigquery-public-data.usa_names.usa_1910_2013`
    WHERE state = 'TX'
    GROUP BY name, state
    ORDER BY total_people DESC
    LIMIT 20
"""
query_job = client.query(query)  # Make an API request.

print("The query data:")
for row in query_job:
    # Row values can be accessed by field name or index.
    print("name={}, count={}".format(row[0], row["total_people"]))
```

Here for example we don't use the .gcp crendentials file, we use the current gpc profile loaded where the script runs (and it would be the same case within a kubernetes pod)

**Comment by ahuang11** [comment]
If I'm not mistaken, I think you can initialize GcpCredentials without service_account_file or service_account_info, e.g. `credentials=GcpCredentials()`, and it would infer from the local env. Let me know if that works.

**Comment by ahuang11** [comment]
I guess I was mistaken; the output profile wouldn't contain those info. The PR above should fix it.
