### ISSUE TITLE
Edit official run dbt in production docs

### ISSUE THREAD

**Issue by sungchun12** [PrefectHQ/prefect-dbt#7]
https://docs.getdbt.com/docs/running-a-dbt-project/running-dbt-in-production/#using-prefect

Replace the above link with nice screenshot examples and reference code example hyperlinks

Keep in mind you'll likely ADD onto the existing docs as this integration is for prefect 2.0 orion. Prefect 1.0 run in production docs are still relevant for 1.0 purposes.

**Comment by sungchun12** [comment]
To be assigned to Bela

**Comment by sungchun12** [comment]
@belasobral93

**Comment by ahuang11** [comment]
Hi, we were wondering if there's anything we can do to help add prefect-dbt to the docs?

**Comment by sungchun12** [comment]
@belasobral93 can you give input here?

**Comment by belasobral93** [comment]
Hi all,

I can prioritize this next week, please stand by!

**Comment by belasobral93** [comment]
### Prefect
If your organization is using [Prefect](https://www.prefect.io/), the way you will run your jobs depends on the version you are on, and whether you are orchestrating dbt cloud or core jobs. A variety of options are described below. 

**- If you are using Prefect 2.0**
  - Invoking dbt cloud jobs
    - Use the [trigger_dbt_cloud_job_run_and_wait_for_completion task](https://prefecthq.github.io/prefect-dbt/#trigger-a-dbt-cloud-job-and-wait-for-completion. As jobs are executing, you can poll dbt to see whether or not the job completes without failures, through the [prefect UI](https://docs.prefect.io/ui/overview/). 

  - Invoking dbt through the cli 
    - Use the [trigger_dbt_cli_command task](https://github.com/PrefectHQ/prefect-dbt/issues/trigger_dbt_cli_command)
	
For details on both of these methods, see [prefect-dbt docs](https://prefecthq.github.io/prefect-dbt/).

**- If you are using Prefect 1.0**
  -  Invoking dbt cloud jobs
    - Trigger dbt Cloud jobs with the [DbtCloudRunJob](https://docs.prefect.io/api/latest/tasks/dbt.html#dbtcloudrunjob) task. Running this task will generate a markdown artifact 						viewable in the Prefect UI. The artifact will contain links to the dbt artifacts generate as a result of the job run.
  - Invoking dbt through the cli
    - Use the [DbtShellTask](https://docs.prefect.io/api/latest/tasks/dbt.html#dbtshelltask) to schedule, execute and monitor your dbt runs.
    - Use the supported [ShellTask](https://docs.prefect.io/api/latest/tasks/shell.html#shelltask) to execute dbt commands through the shell.
    
    @ahuang11 I'd like to use the following images as examples - do you have a better resolution of the DAG (2nd image)? 
    
![dbt_and_prefect_ui](https://user-images.githubusercontent.com/35778239/202576940-79adcc08-6412-4749-83ad-f0b66ba4cddc.png)
![image](https://user-images.githubusercontent.com/35778239/202577019-7df8cb6a-0fc4-4cae-bafb-09dc10b19093.png)

**Comment by belasobral93** [comment]
@ahuang11 wanted to make sure you saw my ask ^

**Comment by ahuang11** [comment]
Thanks for the reminder! Also cc @desertaxle 

I fixed some hyperlinks and cleaned up the formatting a bit. Also maybe you can use this image?
https://user-images.githubusercontent.com/12350579/186269036-01f1090f-1887-433d-8331-ee7c8b315dd5.png

---

# Prefect

If your organization is using [Prefect](https://www.prefect.io/), the way you will run your jobs depends on the version you are on, and whether you are orchestrating dbt Cloud or core jobs. A variety of options are described below.

## On Prefect 2:

### dbt Cloud

Use the [trigger_dbt_cloud_job_run_and_wait_for_completion flow](https://prefecthq.github.io/prefect-dbt/cloud/jobs/#prefect_dbt.cloud.jobs.trigger_dbt_cloud_job_run_and_wait_for_completion). As jobs are executing, you can poll dbt to see whether or not the job completes without failures, through the [prefect UI](https://docs.prefect.io/ui/overview/).

### dbt Core 

Use the [trigger_dbt_cli_command task](https://prefecthq.github.io/prefect-dbt/cli/commands/#prefect_dbt.cli.commands.trigger_dbt_cli_command)

For details on both of these methods, see [prefect-dbt docs](https://prefecthq.github.io/prefect-dbt/).

## On Prefect 1

### dbt Cloud

- Trigger dbt Cloud jobs with the [DbtCloudRunJob](https://docs.prefect.io/api/latest/tasks/dbt.html#dbtcloudrunjob) task. Running this task will generate a markdown artifact viewable in the Prefect UI. The artifact will contain links to the dbt artifacts generate as a result of the job run.

### dbt Core

Use the [DbtShellTask](https://docs.prefect.io/api/latest/tasks/dbt.html#dbtshelltask) to schedule, execute and monitor your dbt runs. Use the supported [ShellTask](https://docs.prefect.io/api/latest/tasks/shell.html#shelltask) to execute dbt commands through the shell.

**Comment by belasobral93** [comment]
@ahuang11 thank you! If you want to give the language and images a run by your marketing team, let me know and I can get the approval from our docs/partnership team. If not, I'll go ahead and submit this draft tomorrow.

**Comment by ahuang11** [comment]
@belasobral93 thanks; I think it can be submitted as a draft! Curious if dbt team is open to updating this in the future (like in 3-6 months)?

**Comment by ahuang11** [comment]
Thank you!

**Comment by belasobral93** [comment]
[Changes are live!
](https://docs.getdbt.com/docs/deploy/deployments#prefect)
